package countingdnanucleotides

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

type testCase struct {
	Description string
	DNA         string
	Symbols     map[string]int
}

var testCases = []testCase{
	testCase{
		Description: "Empty DNA string",
		DNA:         "",
		Symbols:     map[string]int{},
	},
	testCase{
		Description: "Basic DNA string",
		DNA:         "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC",
		Symbols:     map[string]int{"A": 20, "C": 12, "G": 17, "T": 21},
	},
	testCase{
		Description: "Lowercase DNA string",
		DNA:         "agcttttcattctgactgcaacgggcaatatgtctctgtgtggattaaaaaaagagtgtctgatagcagc",
		Symbols:     map[string]int{"A": 20, "C": 12, "G": 17, "T": 21},
	},
	testCase{
		Description: "Large DNA string",
		DNA:         "GGTAGACGATCATTCAATCGATGACCTAGCTCTGGTCCGGGGTATATGCTAGCGAGACAGCACGACTAATTACGCATTTCCTTACACTTGCTGGGAATAAGAAGTAAGCAAACTATGAACAATAGGATTTTAGGCGTGGTAAACCCCACGACGTAGTGCCGGTACGGGGTAGTCAACCCGTTCCAACACATGTATTTAGAAGTGAGTGCTGCTCCCCGGCCGAGTAGCGGACCGACCCTCGTTGGCTTTCCAGGACGTCGTGTTGCAATTCAAGTGCGCTGAAGGTCAGTCAATGAGCTGGGTGCCCCTCCACTCGATAGCCCAAATCATCCGGTGGTGTTAACGACTCGATTTAGTTTCATTAAGGAAGTCGTCGGACCCGCGCTAAACCACACAGGCTGTATACGACGTGGGCGGATCGTGCCGGTGAATATCGGCGAATGTGTGCGAACCCATAAGTTAACATACTTTAGGCTTGTCGAGCCTAATCTAAGTTTGCTTCACTCGAGCAACCCAGCCTTGGTGCTATTATGCACCAATTTGTCGGCGAGACTGTTTTCGAACTTCTGCAACTTTCGTGTTGCGTTCACGATATGGCGAGTAGTTTACCGTTCAGTGCTCGGGTTGCGTTATCCGTCCAAAGTAATTTCCGTTGCAGTCGGTGTTTGTCGTTTCGCGCACAAATTAATTCTGCTAGAGATACGATAGCTTATTACGCCACAGACCCCACTAACTCCATAATCCACCGAAGGGGCTTGCTCCTCCCAAGTCCTAAGAGCGCTTGATTTAACGATCAAGCATCGACAACGACTTCGCTTTTCTGGTAGAAACGCAACAGGGCGGTCGAGTGGATGGAACGATATGAATATGCGATCTCGTCTAATATACACCAAATTCCTCCAGAGCAGTCTCCGTGAGGTAGCCGGCCGTGCCATAGAAATGACGGCTCTCCGTCGCGCTGTTCCTATAGAATTATTGATTGC",
		Symbols:     map[string]int{"A": 239, "C": 245, "G": 243, "T": 256},
	},
}

func Test(t *testing.T) {
	for _, tC := range testCases {
		t.Run(tC.Description, func(t *testing.T) {
			SymbolsActual := Count(tC.DNA)
			assert.Equal(t, tC.Symbols, SymbolsActual)
		})
	}
}
